<h2 style="text-align: center;"><strong>LEGAL STATEMENT</strong></h2>
<p>&nbsp;</p>
<h3><strong>TERMS &amp; CODITIONS OF USE/ LEGAL NOTICE</strong></h3>
<p style="text-align: justify;">IMPORTANT! Please read carefully the following terms and conditions "Terms" governing your use (including access, browsing and/or use of any interactive features) of those portions of VVVLUXURY website accessible at www.vvvlux.com, as well as and including any other VVVLUXURY websites or web pages accessible through VVVLUXURY website or other promotional websites that VVVLUXURY hosts or sponsors such as mini-sites or pages on third party social networking services, directed at consumers in the United Arab Emirates, including those portions of VVVLUXURY website accessible by going to www.vvvlux.com and selecting &ldquo;United Arab Emirates&rdquo; under the listings that appear below &ldquo;Arabian&rdquo; on the link, (collectively the &ldquo;Sites&rdquo;).</p>
<p style="text-align: justify;">Please see the separate terms of use applicable to other country-specific or region-specific web pages available on those pages when you access them through www.vvvlux.com or through other promotional websites.</p>
<h3><strong>PRIVACY POLICY</strong></h3>
<p style="text-align: justify;">VVVLuxury companies worldwide "VVVLUXURY" recognize the importance of protecting the privacy of all consumers &ldquo;you&rdquo; or &ldquo;users&rdquo; who visit the VVVLUXURY hosted or sponsored websites. We also believe it is important to inform you about how we will use your personal information, and to give you choices about the use of this data. For these reasons, we encourage you to read this Privacy Policy carefully.</p>
<p style="text-align: justify;">This Privacy Policy is directed and applicable to individuals who visit the sections of VVVLUXURY website accessible at www.vvvlux.com, as well as and including any other VVVLUXURY websites or web pages accessible through the VVVLUXURY website or other promotional websites that VVVLUXURY hosts or sponsors such as mini-sites or pages on third party social networking services, directed at consumers in the United Arab Emirates, including those sections figuring on VVVLUXURY website accessible by going to www.vvvlux.com, selecting &ldquo;Arabian&rdquo; and clicking on &ldquo;United Arab Emirates&rdquo; under the listings that appear below &ldquo;Arab&rdquo;, (referred to collectively as the &ldquo;Sites&rdquo;). This Privacy Policy applies only to information collected by us via the Sites and does not cover any other website, including other VVVLuxury country-specific pages or region-specific pages intended for non-United Arab Emirates users. The personal information gathered through the Sites is sent directly to servers located in UAE. However we may send your personal information to other countries for the purposes figuring below.</p>
<p style="text-align: justify;">The laws of the United Arab Emirates shall apply to the collection of Personal Information (as defined below in section 2.a.) through the Sites. The laws of the United Arab Emirates and other countries to which we may transfer your personal information may not provide a level of protection equivalent to the laws in your home country, if you are accessing web pages intended for United Arab Emirates consumers from outside the UAE.</p>
<h3><strong>COLLECTION AND USE OF INFORMATION</strong></h3>
<h4><strong>1. Personal Information</strong></h4>
<p style="text-align: justify;">While users can view our website by browsing anonymously, we collect identifiable personal information (&ldquo;Personal Information&rdquo;) about Sites users when they voluntarily provide it in the course of shopping on the Sites, voluntarily registering or otherwise signing up with the Sites, or contacting us via the Sites. Sites users may provide Personal Information for various reasons including, but not limited to, obtaining newsletters, product information, event information, and services, answering surveys, participating in contests, receiving notices of other promotional opportunities, and making purchases. The type of Personal Information that we may collect includes the name, address, phone number, email address and purchase information such as credit or debit card information used to facilitate the sale transactions. We may also use the information that you provide to create a personal customer profile in order to let you know of products or events that may be of interest to you, to streamline future purchases, and for customer service purposes. We may combine Personal Information we collect on the Sites with other information we collect offline about users to improve the structuring of marketing or website content or for other purposes, such as internal research. For information on how to opt-out of allowing us to use your Personal Information for marketing purposes, see section 6 below.</p>
<h4 style="text-align: justify;">2. Non-Personal Information</h4>
<p style="text-align: justify;">We collect certain aggregate and non-personal information when you visit the Sites. This information does not relate to a single identifiable visitor. It tells us such things as how many users visited the Sites and the pages accessed. Collecting this information helps us tailor our Sites to our visitors.</p>
<p style="text-align: justify;">When you visit the Sites to browse, read or download information, we automatically collect standard computer information that your browser sends to every website you visit, such as your IP address, browser type and language, access times and referring website addresses. We generally do not link standard computer information to anything that will allow us to identify users unless to enforce compliance with our rules or terms of service or to protect our service, sites, users or others. We also may collect aggregate and non-personal information through &ldquo;cookies&rdquo; or &ldquo;web beacons,&rdquo; as explained below.</p>
<p style="text-align: justify;"><strong>Cookies:</strong> Cookies are pieces of information that any website may transfer to your browser that are then stored in your computer system. Cookies are returned to the website that deposited them when a visitor returns to that site. Cookies tell us, for example, whether a user is a first time visitor or has visited the Sites before and what areas of the websites are of greatest interest to the user. The deposit of cookies by the Sites may enhance your online experience by allowing us to save your preferences for your next visit. Our cookies may also measure the general activity on the Sites, which allows us to determine which areas and features are most popular. This information allows us to make improvements to our Sites. Most web browsers are set up to accept cookies. You can, however, reset your browser to refuse all cookies or to indicate when a cookie is being sent. If you choose to decline cookies, some of the functionality of the Sites may be impaired. Web Beacons: Web beacons, also known as &ldquo;clear gifs,&rdquo; &ldquo;one-pixel gifs,&rdquo; &ldquo;web bugs,&rdquo; &ldquo;Internet tags&rdquo; or &ldquo;pixel tags,&rdquo; are small graphic images on a website or in an e-mail that allow us and third parties to monitor the activity on the Sites or to make cookies more effective. Web beacons allow us, or third parties working on our behalf, to gauge and enhance the effectiveness of our marketing by transmitting information about whether you follow links in our e-mails or websites, and by gathering information about the sites you visit before and after visiting our websites. We use log files to store the data that is collected through Web beacons.</p>
<h3><strong>SHARING OF PERSONAL INFORMATION</strong></h3>
<p style="text-align: justify;">Subject to the following paragraphs and the disclosures discussed in them, we will neither disclose nor sell any information about you to a party unaffiliated with us unless (1) required to do so by law or legal process; (2) required to do so by law enforcement authorities or other government officials; (3) we believe disclosure is necessary or appropriate to prevent physical harm, financial loss or injury to, or interference with, our rights or property or the rights or property of our users or others, or in connection with an investigation of suspected or actual illegal activity; (4) we reasonably believe that you have used information from the Sites in order to commit unlawful acts or acts that may endanger the health and/or safety of the public; and/or (5) we believe the law in good faith requires such disclosure. We may appoint third party service providers to administer and/or operate certain functions or services on our behalf, the proper performance of which may require a transfer of the information submitted by you. The functions or services include, for example, administering the Sites, delivery of products requested or ordered by you, and delivery of marketing or other communications to you about our products, services or special events. Any such transfer shall be subject to confidentiality and security obligations and for the sole purpose of the performance of those functions or services. We may also share your Personal Information with other third parties for joint marketing and promotions of products, services or events that may be of interest to you. Any transfers of Personal Information shall be subject to confidentiality and security obligations and for the sole purpose of the performance of those obligations. For information on how to opt-out of allowing us to use your Personal Information for marketing, see section 6 below. You should be aware, however, that even if you opt-out of allowing us to use your information for marketing campaigns, we may still share certain information with third parties to comply with legal obligations. For example, if you have opted out of marketing emails from us, we may have to provide your email address to a third party we jointly market with to comply with your opt-out request.</p>
<h3><strong>UNSOLICITED MATERIALS</strong></h3>
<p style="text-align: justify;">Through the Sites, we request that you provide to us certain types of information so that we may better serve you. The requested information may include questions and comments about our products. Please do not provide us with materials, including but not limited to business, advertising, creative, marketing or any other types of proposals, concepts, know-how, ideas and the like ("Unsolicited Materials"). All Unsolicited Materials, including any unsolicited Personal Information (for example, Personal Information provided not in response to a specific request for such information, but in a free form text box), that we receive will not be subject to this Privacy Policy. By submitting any Unsolicited Materials, you agree that we shall have the sole discretion as to how to utilize such Unsolicited Materials and you automatically provide to us a perpetual, royalty free license to such end. If any Unsolicited Materials that you provide to us are protected by third party copyright, trademark or other proprietary rights, you agree to indemnify, defend, and hold harmless VVVLUXURY, its parent, subsidiaries and/or affiliated entities, and its and their respective officers, directors, employees, agents, licensors, representatives, and third party providers (collectively, "the VVVLUXURY Indemnitees"), against any claims or actions brought against any of the VVVLUXURY Indemnitees arising out of or relating to our use or possession of the Unsolicited Materials.</p>
<h3><strong>SECURITY</strong></h3>
<p style="text-align: justify;">Protecting your information is of primary concern to us. We store the information that we collect on secure servers and otherwise take reasonable precautions to protect your Personal Information.</p>
<p style="text-align: justify;">However, we cannot warrant and do not represent that our level of security meets or exceeds any specific standards. No Internet transmission is 100% secure or error-free, nor is stored data free from vulnerabilities. We cannot guarantee the security of our websites, databases or services, nor can we guarantee that the information you supply will not be intercepted while being transmitted to us over the Internet. We are not responsible for the actions of third parties.</p>
<h3><strong>UPDATING YOUR PERSONAL INFORMATION AND OPTING OUT OF MARKETING COMMUNICATIONS</strong></h3>
<p style="text-align: justify;">If you want to update your Personal Information, you may access your personal profile online, if one exists or is accessible, and change your entry. Generally, any online profile that exists is accessible at the &ldquo;Fragrance,&rdquo; &ldquo;Makeup&rdquo; and/or &ldquo;Skincare&rdquo; pages by clicking on &ldquo;Account&rdquo; or &ldquo;Login&rdquo; and entering the applicable information. You may choose to unsubscribe from marketing emails by utilizing the &ldquo;unsubscribe&rdquo; link on our marketing emails. Please note that any requests may take up to six to eight weeks to become effective. Even if you opt-out of marketing communications, we may still contact you to send you important information regarding the operation or administration of your personal profile or other non-marketing information. For additional information regarding our policies regarding the Sites please see <a href="https://services.chanel.com/en_ME/policies/legal/">Legal Statement.</a></p>
<h3><strong>CORPORATE CHANGE OF CONTROL</strong></h3>
<p style="text-align: justify;">Personal Information collected over the Sites may be transferred as part of any merger, acquisition or sale of company assets, as well as in the unlikely event of insolvency, bankruptcy, or receivership in which Personal Information would be transferred to another entity.</p>
<h3><strong>CHANGES TO THIS PRIVACY</strong></h3>
<p style="text-align: justify;">We reserve the right, in our sole discretion, to modify, alter or otherwise update this policy at any time and you agree to be bound by such modifications, alterations or updates. We will notify you of material changes to this Privacy Policy by posting the revised policy with the date it was revised on this page and if you have registered with us, we may notify you by email to your email address of record. Your continued use (including access, browsing and/or use of any interactive feature) of our Sites constitutes your agreement to this Privacy Policy and any updates. We encourage you to periodically review this Privacy Policy to stay informed about how we are protecting the Personal Information we collect.</p>
<h3><strong>CONTACTING US</strong></h3>
<p style="text-align: justify;">If you have any questions or comments about this Privacy Policy, or if you would like us to update any information we have about you, please contact us by writing to us at:</p>
<p><strong>VVVLUXURY</strong></p>
<p style="text-align: justify;">c/o REIGN Corporates<br />P.O.Box: 26877, <br />Dubai, UAE.</p>
<p style="text-align: justify;">&nbsp;</p>
<p>&copy; 2019 VVVLUXURY, All Rights Reserved.</p>
<h3><strong>OWNERSHIP RIGHTS/ USE OF SITES MATERIALS</strong></h3>
<p style="text-align: justify;">VVVLuxury. and/or its worldwide affiliates (&ldquo;VVVLUXURY&rdquo;)) own all right, title and interest in and to the Sites and/or own the content and applications on the Sites (including on social network websites).</p>
<p style="text-align: justify;">VVVLUXURY owns all copyrights for all material on the Sites or has a valid right from a third party to use the material on the Sites. VVVLUXURY also owns all trademarks, service marks, trade names, logos and domain names used on or in connection with the Sites or has a valid right from a third party to use any such material. Any modification or use of the materials from the Sites for any purpose not explicitly permitted is a violation of VVVLUXURY's copyright and other proprietary rights.<br />No part of the Sites may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any manner whatsoever, except for viewing purposes, without the prior written consent of VVVLUXURY. This prohibition also includes framing any content from the Sites, as well as unauthorized linking.</p>
<h3><strong>DISCLAIMER / LIMITATION ON LIABILITY</strong></h3>
<p style="text-align: justify;">Use of and browsing in the Sites are at your own risk. Neither VVVLUXURY nor any party representing or otherwise affiliated with VVVLUXURY in creating or presenting the Sites are liable for any direct, indirect, special, punitive, incidental, exemplary or consequential damages arising out of your use of the Sites. To the extent permitted by law and without limiting any of the foregoing, everything on the Sites is provided to you on as "as is" basis, without warranty, either express or implied, of any kind, including, but not limited to, the implied warranties of merchantability, fitness for a specific purpose, freedom from computer virus, or non-infringement. Because some jurisdictions do not allow limitations on implied warranties, or limitation of liability for consequential or incidental damages, the above limitations may not apply to you. Please check your local laws. Solicited information that you submit to VVVLUXURY by email in order to register or sign up, purchase products and/or to submit appropriate questions to the Sites are subject to our <a href="https://services.chanel.com/en_ME/policies/privacy/">Privacy Policy</a>. All unsolicited reviews, comments or other submissions, including ideas, concepts, techniques, know-how and the like, shall not be treated as confidential by VVVLUXURY and VVVLUXURY may use such materials in any manner that it deems appropriate. For more information on this topic, please see our <a href="https://services.chanel.com/en_ME/policies/privacy/">Privacy Policy</a>.</p>
<h3>LINKS</h3>
<p style="text-align: justify;">VVVLUXURY is not responsible for third party websites that link to or from the Sites. VVVLUXURY does not endorse any such sites or the goods or services offered on such sites. VVVLUXURY disclaims all responsibility for the accuracy of any of the information provided on such linked sites and any goods or services provided or purchased from such sites. VVVLUXURY shall not be held liable or responsible for the content of any sites that link to or from the Sites.</p>
<h3>ACCURAY OF INFORMATION</h3>
<p style="text-align: justify;">VVVLUXURY takes reasonable steps to ensure the accuracy of the information included in the Sites. However, VVVLUXURY takes no responsibility for errors or omissions in the content of the Sites and does not guarantee the accuracy, completeness or timeliness of information provided on the Sites. Information provided on the Sites is subject to change at any time without prior notice.</p>
<h3>NO WAIVER</h3>
<p style="text-align: justify;">The failure on the part of VVVLUXURY to enforce any part of these Terms shall not constitute a waiver of any of VVVLUXURY's rights hereunder for past or future actions.</p>
<h3><strong>JURISDICTION</strong></h3>
<p style="text-align: justify;">Any dispute over the content or use of the Sites shall be governed by the substantive laws of the federal and state courts of United Arab Emirates.</p>
<h3>MISCELLANEOUS</h3>
<p style="text-align: justify;">You acknowledge and agree that these Terms, together with our <a href="https://services.chanel.com/en_ME/policies/privacy/">Privacy Policy</a>, constitute the entire agreement between you and VVVLUXURY with respect to the use of the Sites. VVVLUXURY may change these Terms at any time by posting changes on the Sites. Any changes are effective immediately upon posting. The continued use of the Sites constitutes your agreement to any revised Terms. BY USING THE SITES, YOU SIGNIFY YOUR UNDERSTANDING AND AGREEMENT TO COMPLY WITH THE TERMS &amp; CONDITIONS OF USE. LAST UPDATED: DECEMBER 2019 &copy; VVVLUXURY, 2019 All Rights Reserved.</p>